export const iconNames = [
  { value: 'briefcase-solid', label: 'Briefcase solid' },
  { value: 'cc-apple-pay-brands-solid', label: 'Cc apple pay brands solid' },
  { value: 'cc-mastercard-brands-solid', label: 'Cc mastercard brands solid' },
  { value: 'cc-visa-brands-solid', label: 'Cc visa brands solid' },
  { value: 'circle-check-solid', label: 'Circle check solid' },
  { value: 'circle-info-solid', label: 'Circle info solid' },
  { value: 'clock-regular', label: 'Clock regular' },
  { value: 'comment-solid', label: 'Comment solid' },
  { value: 'envelope-solid', label: 'Envelope solid' },
  { value: 'facebook-brands-solid', label: 'Facebook brands solid' },
  { value: 'file-circle-check-solid', label: 'File circle check solid' },
  { value: 'folder-open-solid', label: 'Folder open solid' },
  { value: 'globe-solid', label: 'Globe solid' },
  { value: 'handshake-solid', label: 'Handshake solid' },
  { value: 'instagram-brands-solid', label: 'Instagram brands solid' },
  { value: 'key-solid', label: 'Key solid' },
  { value: 'lightbulb-solid', label: 'Lightbulb solid' },
  { value: 'linkedin-brands-solid', label: 'Linkedin brands solid' },
  { value: 'paperclip-solid', label: 'Paperclip solid' },
  { value: 'paypal-brands-solid', label: 'Paypal brands solid' },
  { value: 'pen-fancy-solid', label: 'Pen fancy solid' },
  { value: 'phone-volume-solid', label: 'Phone volume solid' },
  { value: 'signature-solid', label: 'Signature solid' },
  { value: 'thumbtack-solid', label: 'Thumbtack solid' },
  { value: 'truck-fast-solid', label: 'Truck fast solid' },
  { value: 'twitter-brands-solid', label: 'Twitter brands solid' },
  { value: 'users-solid', label: 'Users solid' },
  { value: 'youtube-brands-solid', label: 'Youtube brands solid' },
]
