export const iconNames = {
  'Briefcase': 'briefcase-solid',
  'Apple Pay': 'cc-apple-pay-brands-solid',
  'Mastercard': 'cc-mastercard-brands-solid',
  'Visa': 'cc-visa-brands-solid',
  'Circle Check': 'circle-check-solid',
  'Circle Info': 'circle-info-solid',
  'Clock': 'clock-regular',
  'Comment': 'comment-solid',
  'Envelope': 'envelope-solid',
  'Facebook': 'facebook-brands-solid',
  'File Circle Check': 'file-circle-check-solid',
  'Folder Open': 'folder-open-solid',
  'Globe': 'globe-solid',
  'Handshake': 'handshake-solid',
  'Instagram': 'instagram-brands-solid',
  'Key': 'key-solid',
  'Lightbulb': 'lightbulb-solid',
  'Linkedin': 'linkedin-brands-solid',
  'Paperclip': 'paperclip-solid',
  'Paypal': 'paypal-brands-solid',
  'Pen Fancy': 'pen-fancy-solid',
  'Phone Volume': 'phone-volume-solid',
  'Signature': 'signature-solid',
  'Thumbtack': 'thumbtack-solid',
  'Truck Fast': 'truck-fast-solid',
  'Twitter': 'twitter-brands-solid',
  'Users': 'users-solid',
  'Youtube': 'youtube-brands-solid',
}
