export declare const iconNames: {
    Briefcase: string;
    'Apple Pay': string;
    Mastercard: string;
    Visa: string;
    'Circle Check': string;
    'Circle Info': string;
    Clock: string;
    Comment: string;
    Envelope: string;
    Facebook: string;
    'File Circle Check': string;
    'Folder Open': string;
    Globe: string;
    Handshake: string;
    Instagram: string;
    Key: string;
    Lightbulb: string;
    Linkedin: string;
    Paperclip: string;
    Paypal: string;
    'Pen Fancy': string;
    'Phone Volume': string;
    Signature: string;
    Thumbtack: string;
    'Truck Fast': string;
    Twitter: string;
    Users: string;
    Youtube: string;
};
